# Auto-generated by extract.rb
# API Documentation: https://docs.opnsense.org/development/api/core/auth.html

from pyopnsapi import client


class GroupClient(client.OPNClient):
    """A client for interacting with the Auth/Group endpoint.

    Model Schema: https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Auth/Group.xml

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def add(self):
      return self._post("auth/group/add")

    def get_search(self):
      return self._get("auth/group/search")

    def post_search(self):
      return self._post("auth/group/search")


class PrivClient(client.OPNClient):
    """A client for interacting with the Auth/Priv endpoint.

    Model Schema: https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Auth/Priv.xml

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def get(self):
      return self._get("auth/priv/get")

    def search(self):
      return self._get("auth/priv/search")

    def set(self):
      return self._post("auth/priv/set")


class UserClient(client.OPNClient):
    """A client for interacting with the Auth/User endpoint.

    Model Schema: https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Auth/User.xml

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def add(self):
      return self._post("auth/user/add")

    def download(self):
      return self._get("auth/user/download")

    def new_otp_seed(self):
      return self._get("auth/user/new_otp_seed")

    def get_search(self):
      return self._get("auth/user/search")

    def post_search(self):
      return self._post("auth/user/search")

    def search_api_key(self):
      return self._get("auth/user/search_api_key")

    def upload(self):
      return self._post("auth/user/upload")

