# Auto-generated by extract.rb
# API Documentation: https://docs.opnsense.org/development/api/core/cron.html

from pyopnsapi import client


class ServiceClient(client.OPNClient):
    """A client for interacting with the Cron/Service endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def reconfigure(self):
      return self._post("cron/service/reconfigure")


class SettingsClient(client.OPNClient):
    """A client for interacting with the Cron/Settings endpoint.

    Model Schema: https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Cron/Cron.xml

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def add_job(self):
      return self._post("cron/settings/add_job")

    def get(self):
      return self._get("cron/settings/get")

    def get_search_jobs(self):
      return self._get("cron/settings/search_jobs")

    def post_search_jobs(self):
      return self._post("cron/settings/search_jobs")

    def set(self):
      return self._post("cron/settings/set")

