# Auto-generated by extract.rb
# API Documentation: https://docs.opnsense.org/development/api/core/dhcpv6.html

from pyopnsapi import client


class LeasesClient(client.OPNClient):
    """A client for interacting with the Dhcpv6/Leases endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def search_lease(self):
      return self._get("dhcpv6/leases/search_lease")

    def search_prefix(self):
      return self._get("dhcpv6/leases/search_prefix")


class ServiceClient(client.OPNClient):
    """A client for interacting with the Dhcpv6/Service endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def reconfigure(self):
      return self._post("dhcpv6/service/reconfigure")

    def restart(self):
      return self._post("dhcpv6/service/restart")

    def start(self):
      return self._post("dhcpv6/service/start")

    def status(self):
      return self._get("dhcpv6/service/status")

    def stop(self):
      return self._post("dhcpv6/service/stop")

