# Auto-generated by extract.rb
# API Documentation: https://docs.opnsense.org/development/api/core/dhcrelay.html

from pyopnsapi import client


class ServiceClient(client.OPNClient):
    """A client for interacting with the Dhcrelay/Service endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def reconfigure(self):
      return self._post("dhcrelay/service/reconfigure")


class SettingsClient(client.OPNClient):
    """A client for interacting with the Dhcrelay/Settings endpoint.

    Model Schema: https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/DHCRelay/DHCRelay.xml

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def add_dest(self):
      return self._post("dhcrelay/settings/add_dest")

    def add_relay(self):
      return self._post("dhcrelay/settings/add_relay")

    def get(self):
      return self._get("dhcrelay/settings/get")

    def get_search_dest(self):
      return self._get("dhcrelay/settings/search_dest")

    def post_search_dest(self):
      return self._post("dhcrelay/settings/search_dest")

    def get_search_relay(self):
      return self._get("dhcrelay/settings/search_relay")

    def post_search_relay(self):
      return self._post("dhcrelay/settings/search_relay")

    def set(self):
      return self._post("dhcrelay/settings/set")

