# Auto-generated by extract.rb
# API Documentation: https://docs.opnsense.org/development/api/core/dnsmasq.html

from pyopnsapi import client


class LeasesClient(client.OPNClient):
    """A client for interacting with the Dnsmasq/Leases endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def search(self):
      return self._get("dnsmasq/leases/search")


class ServiceClient(client.OPNClient):
    """A client for interacting with the Dnsmasq/Service endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def reconfigure(self):
      return self._post("dnsmasq/service/reconfigure")

    def restart(self):
      return self._post("dnsmasq/service/restart")

    def start(self):
      return self._post("dnsmasq/service/start")

    def status(self):
      return self._get("dnsmasq/service/status")

    def stop(self):
      return self._post("dnsmasq/service/stop")


class SettingsClient(client.OPNClient):
    """A client for interacting with the Dnsmasq/Settings endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def add_boot(self):
      return self._post("dnsmasq/settings/add_boot")

    def add_domain(self):
      return self._post("dnsmasq/settings/add_domain")

    def add_host(self):
      return self._post("dnsmasq/settings/add_host")

    def add_option(self):
      return self._post("dnsmasq/settings/add_option")

    def add_range(self):
      return self._post("dnsmasq/settings/add_range")

    def add_tag(self):
      return self._post("dnsmasq/settings/add_tag")

    def download_hosts(self):
      return self._get("dnsmasq/settings/download_hosts")

    def get(self):
      return self._get("dnsmasq/settings/get")

    def get_tag_list(self):
      return self._get("dnsmasq/settings/get_tag_list")

    def get_search_boot(self):
      return self._get("dnsmasq/settings/search_boot")

    def post_search_boot(self):
      return self._post("dnsmasq/settings/search_boot")

    def get_search_domain(self):
      return self._get("dnsmasq/settings/search_domain")

    def post_search_domain(self):
      return self._post("dnsmasq/settings/search_domain")

    def get_search_host(self):
      return self._get("dnsmasq/settings/search_host")

    def post_search_host(self):
      return self._post("dnsmasq/settings/search_host")

    def get_search_option(self):
      return self._get("dnsmasq/settings/search_option")

    def post_search_option(self):
      return self._post("dnsmasq/settings/search_option")

    def get_search_range(self):
      return self._get("dnsmasq/settings/search_range")

    def post_search_range(self):
      return self._post("dnsmasq/settings/search_range")

    def get_search_tag(self):
      return self._get("dnsmasq/settings/search_tag")

    def post_search_tag(self):
      return self._post("dnsmasq/settings/search_tag")

    def set(self):
      return self._post("dnsmasq/settings/set")

    def upload_hosts(self):
      return self._post("dnsmasq/settings/upload_hosts")

