# Auto-generated by extract.rb
# API Documentation: https://docs.opnsense.org/development/api/core/ids.html

from pyopnsapi import client


class ServiceClient(client.OPNClient):
    """A client for interacting with the Ids/Service endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def drop_alert_log(self):
      return self._post("ids/service/drop_alert_log")

    def get_alert_logs(self):
      return self._get("ids/service/get_alert_logs")

    def query_alerts(self):
      return self._post("ids/service/query_alerts")

    def reconfigure(self):
      return self._post("ids/service/reconfigure")

    def reload_rules(self):
      return self._post("ids/service/reload_rules")

    def restart(self):
      return self._post("ids/service/restart")

    def start(self):
      return self._post("ids/service/start")

    def status(self):
      return self._get("ids/service/status")

    def stop(self):
      return self._post("ids/service/stop")


class SettingsClient(client.OPNClient):
    """A client for interacting with the Ids/Settings endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def add_policy(self):
      return self._post("ids/settings/add_policy")

    def add_policy_rule(self):
      return self._post("ids/settings/add_policy_rule")

    def add_user_rule(self):
      return self._post("ids/settings/add_user_rule")

    def check_policy_rule(self):
      return self._get("ids/settings/check_policy_rule")

    def get(self):
      return self._get("ids/settings/get")

    def get_rulesetproperties(self):
      return self._get("ids/settings/get_rulesetproperties")

    def list_rule_metadata(self):
      return self._get("ids/settings/list_rule_metadata")

    def list_rulesets(self):
      return self._get("ids/settings/list_rulesets")

    def search_installed_rules(self):
      return self._post("ids/settings/search_installed_rules")

    def get_search_policy(self):
      return self._get("ids/settings/search_policy")

    def post_search_policy(self):
      return self._post("ids/settings/search_policy")

    def get_search_policy_rule(self):
      return self._get("ids/settings/search_policy_rule")

    def post_search_policy_rule(self):
      return self._post("ids/settings/search_policy_rule")

    def get_search_user_rule(self):
      return self._get("ids/settings/search_user_rule")

    def post_search_user_rule(self):
      return self._post("ids/settings/search_user_rule")

    def set(self):
      return self._post("ids/settings/set")

    def set_rulesetproperties(self):
      return self._post("ids/settings/set_rulesetproperties")

