# Auto-generated by extract.rb
# API Documentation: https://docs.opnsense.org/development/api/core/routes.html

from pyopnsapi import client


class GatewayClient(client.OPNClient):
    """A client for interacting with the Routes/Gateway endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def status(self):
      return self._get("routes/gateway/status")


class RoutesClient(client.OPNClient):
    """A client for interacting with the Routes/Routes endpoint.

    Model Schema: https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Routes/Route.xml

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def addroute(self):
      return self._post("routes/routes/addroute")

    def get(self):
      return self._get("routes/routes/get")

    def reconfigure(self):
      return self._post("routes/routes/reconfigure")

    def get_searchroute(self):
      return self._get("routes/routes/searchroute")

    def post_searchroute(self):
      return self._post("routes/routes/searchroute")

    def set(self):
      return self._post("routes/routes/set")

