# Auto-generated by extract.rb
# API Documentation: https://docs.opnsense.org/development/api/core/routing.html

from pyopnsapi import client


class SettingsClient(client.OPNClient):
    """A client for interacting with the Routing/Settings endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def add_gateway(self):
      return self._post("routing/settings/add_gateway")

    def get(self):
      return self._get("routing/settings/get")

    def reconfigure(self):
      return self._post("routing/settings/reconfigure")

    def search_gateway(self):
      return self._get("routing/settings/search_gateway")

    def set(self):
      return self._post("routing/settings/set")

