# Auto-generated by extract.rb
# API Documentation: https://docs.opnsense.org/development/api/core/trust.html

from pyopnsapi import client


class CaClient(client.OPNClient):
    """A client for interacting with the Trust/Ca endpoint.

    Model Schema: https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Trust/Ca.xml

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def add(self):
      return self._post("trust/ca/add")

    def ca_list(self):
      return self._get("trust/ca/ca_list")

    def get_search(self):
      return self._get("trust/ca/search")

    def post_search(self):
      return self._post("trust/ca/search")


class CertClient(client.OPNClient):
    """A client for interacting with the Trust/Cert endpoint.

    Model Schema: https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Trust/Cert.xml

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def add(self):
      return self._post("trust/cert/add")

    def ca_list(self):
      return self._get("trust/cert/ca_list")

    def get_search(self):
      return self._get("trust/cert/search")

    def post_search(self):
      return self._post("trust/cert/search")

    def user_list(self):
      return self._get("trust/cert/user_list")


class CrlClient(client.OPNClient):
    """A client for interacting with the Trust/Crl endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def search(self):
      return self._get("trust/crl/search")


class SettingsClient(client.OPNClient):
    """A client for interacting with the Trust/Settings endpoint.

    Model Schema: https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Trust/General.xml

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def get(self):
      return self._get("trust/settings/get")

    def reconfigure(self):
      return self._post("trust/settings/reconfigure")

    def set(self):
      return self._post("trust/settings/set")

