# Auto-generated by extract.rb
# API Documentation: https://docs.opnsense.org/development/api/core/unbound.html

from pyopnsapi import client


class DiagnosticsClient(client.OPNClient):
    """A client for interacting with the Unbound/Diagnostics endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def dumpcache(self):
      return self._get("unbound/diagnostics/dumpcache")

    def dumpinfra(self):
      return self._get("unbound/diagnostics/dumpinfra")

    def listinsecure(self):
      return self._get("unbound/diagnostics/listinsecure")

    def listlocaldata(self):
      return self._get("unbound/diagnostics/listlocaldata")

    def listlocalzones(self):
      return self._get("unbound/diagnostics/listlocalzones")

    def stats(self):
      return self._get("unbound/diagnostics/stats")


class OverviewClient(client.OPNClient):
    """A client for interacting with the Unbound/Overview endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def is_block_list_enabled(self):
      return self._get("unbound/overview/is_block_list_enabled")

    def is_enabled(self):
      return self._get("unbound/overview/is_enabled")

    def search_queries(self):
      return self._get("unbound/overview/search_queries")


class ServiceClient(client.OPNClient):
    """A client for interacting with the Unbound/Service endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def dnsbl(self):
      return self._get("unbound/service/dnsbl")

    def reconfigure(self):
      return self._post("unbound/service/reconfigure")

    def reconfigure_general(self):
      return self._get("unbound/service/reconfigure_general")

    def restart(self):
      return self._post("unbound/service/restart")

    def start(self):
      return self._post("unbound/service/start")

    def status(self):
      return self._get("unbound/service/status")

    def stop(self):
      return self._post("unbound/service/stop")


class SettingsClient(client.OPNClient):
    """A client for interacting with the Unbound/Settings endpoint.

    Model Schema: https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/models/OPNsense/Unbound/Unbound.xml

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def add_acl(self):
      return self._post("unbound/settings/add_acl")

    def add_forward(self):
      return self._post("unbound/settings/add_forward")

    def add_host_alias(self):
      return self._post("unbound/settings/add_host_alias")

    def add_host_override(self):
      return self._post("unbound/settings/add_host_override")

    def get(self):
      return self._get("unbound/settings/get")

    def get_nameservers(self):
      return self._get("unbound/settings/get_nameservers")

    def get_search_acl(self):
      return self._get("unbound/settings/search_acl")

    def post_search_acl(self):
      return self._post("unbound/settings/search_acl")

    def get_search_forward(self):
      return self._get("unbound/settings/search_forward")

    def post_search_forward(self):
      return self._post("unbound/settings/search_forward")

    def get_search_host_alias(self):
      return self._get("unbound/settings/search_host_alias")

    def post_search_host_alias(self):
      return self._post("unbound/settings/search_host_alias")

    def get_search_host_override(self):
      return self._get("unbound/settings/search_host_override")

    def post_search_host_override(self):
      return self._post("unbound/settings/search_host_override")

    def set(self):
      return self._post("unbound/settings/set")

    def update_blocklist(self):
      return self._post("unbound/settings/update_blocklist")

