# Auto-generated by extract.rb
# API Documentation: https://docs.opnsense.org/development/api/core/wireguard.html

from pyopnsapi import client


class ClientClient(client.OPNClient):
    """A client for interacting with the Wireguard/Client endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def add_client(self):
      return self._get("wireguard/client/add_client")

    def add_client_builder(self):
      return self._post("wireguard/client/add_client_builder")

    def get(self):
      return self._get("wireguard/client/get")

    def get_client_builder(self):
      return self._get("wireguard/client/get_client_builder")

    def list_servers(self):
      return self._get("wireguard/client/list_servers")

    def psk(self):
      return self._get("wireguard/client/psk")

    def get_search_client(self):
      return self._get("wireguard/client/search_client")

    def post_search_client(self):
      return self._post("wireguard/client/search_client")

    def set(self):
      return self._post("wireguard/client/set")


class GeneralClient(client.OPNClient):
    """A client for interacting with the Wireguard/General endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def get(self):
      return self._get("wireguard/general/get")

    def set(self):
      return self._post("wireguard/general/set")


class ServerClient(client.OPNClient):
    """A client for interacting with the Wireguard/Server endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def get(self):
      return self._get("wireguard/server/get")

    def key_pair(self):
      return self._get("wireguard/server/key_pair")

    def get_search_server(self):
      return self._get("wireguard/server/search_server")

    def post_search_server(self):
      return self._post("wireguard/server/search_server")

    def set(self):
      return self._post("wireguard/server/set")


class ServiceClient(client.OPNClient):
    """A client for interacting with the Wireguard/Service endpoint.

    :param str api_key: The API key to use for requests
    :param str api_secret: The API secret to use for requests
    :param str base_url: The base API endpoint for the OPNsense deployment
    :param int timeout: The timeout in seconds for API requests
    """

    def reconfigure(self):
      return self._post("wireguard/service/reconfigure")

    def restart(self):
      return self._post("wireguard/service/restart")

    def show(self):
      return self._get("wireguard/service/show")

    def start(self):
      return self._post("wireguard/service/start")

    def status(self):
      return self._get("wireguard/service/status")

    def stop(self):
      return self._post("wireguard/service/stop")

